version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 794038254814.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ap-flask .
      - docker tag ap-flask 794038254814.dkr.ecr.ca-central-1.amazonaws.com/upadhyay-flask

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 794038254814.dkr.ecr.ca-central-1.amazonaws.com/upadhyay-flask
      - echo Writing imagedefinitions.json file...
      - echo '[{"name":"upadhyay-flask","imageUri":"794038254814.dkr.ecr.ca-central-1.amazonaws.com/upadhyay-flask"}]' > ./imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json 
